services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/eventx

  client:
    build:
      context: ./client
    ports:
      - "4173:4173"
    depends_on:
      - server

volumes:
  mongo-data:
